services:
  nestjs-app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/Gerador
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_module
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27019:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: